<a href="https://colab.research.google.com/github/2303a51546/_10_python-for-data-science/blob/main/python_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A=np.array([[20,30,40],[40,50,60]])
B=np.array([[15,10,25],[20,25,35]])
print(A)
print(B)




[[20 30 40]
 [40 50 60]]
[[15 10 25]
 [20 25 35]]


In [2]:
addition=np.add(A,B)
print(addition)
subtraction=np.subtract(A,B)
print(subtraction)






[[35 40 65]
 [60 75 95]]
[[ 5 20 15]
 [20 25 25]]


In [3]:
import numpy as np
scores = np.random.randint(0, 101, (4, 4))
print("Test Scores (4x4):\n", scores)
row_mean = np.mean(scores, axis=1)
print("\nRow-wise Mean (per student):\n", row_mean)
col_mean = np.mean(scores, axis=0)
print("\nColumn-wise Mean (per subject):\n", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation of all scores:", std_dev)
print("Variance of all scores:", variance)
max_value = np.max(scores)
min_value = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nMaximum Score:", max_value)
print("Minimum Score:", min_value)

Test Scores (4x4):
 [[ 5 43 49 49]
 [44 13  1 79]
 [50 23 36 19]
 [70 64 94 74]]

Row-wise Mean (per student):
 [36.5  34.25 32.   75.5 ]

Column-wise Mean (per subject):
 [42.25 35.75 45.   55.25]

Standard Deviation of all scores: 26.509358606914653
Variance of all scores: 702.74609375

Maximum Score: 94
Minimum Score: 1


In [5]:
import numpy as np
image = np.random.randint(0, 256, (3, 3, 3))
print("Original Image:\n", image)
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)
print("\nAverage Red:", np.mean(red))
print("Average Green:", np.mean(green))
print("Average Blue:", np.mean(blue))
bright = np.clip(np.add(image, 50), 0, 255)
print("\nBrightened Image:\n", bright)
dark = np.clip(np.subtract(image, 50), 0, 255)
print("\nDarkened Image:\n", dark)


Original Image:
 [[[ 26 101  79]
  [242 174 197]
  [ 56 124 117]]

 [[ 15 139  70]
  [239 142 118]
  [  4 102 195]]

 [[  8 172  43]
  [ 90 203  97]
  [173  98 172]]]

Red Channel:
 [[ 26 242  56]
 [ 15 239   4]
 [  8  90 173]]

Green Channel:
 [[101 174 124]
 [139 142 102]
 [172 203  98]]

Blue Channel:
 [[ 79 197 117]
 [ 70 118 195]
 [ 43  97 172]]

Average Red: 94.77777777777777
Average Green: 139.44444444444446
Average Blue: 120.88888888888889

Brightened Image:
 [[[ 76 151 129]
  [255 224 247]
  [106 174 167]]

 [[ 65 189 120]
  [255 192 168]
  [ 54 152 245]]

 [[ 58 222  93]
  [140 253 147]
  [223 148 222]]]

Darkened Image:
 [[[  0  51  29]
  [192 124 147]
  [  6  74  67]]

 [[  0  89  20]
  [189  92  68]
  [  0  52 145]]

 [[  0 122   0]
  [ 40 153  47]
  [123  48 122]]]
